### ISSUE TITLE
Strings (".*?") containing \" won't work

### ISSUE THREAD

**Issue by richi** [kristian/RegexHighlightView#1]
((?<!\)".*?(?<!\)") does a somewhat better job, but is still not perfect, since it does not solve //"

Anyhow, great job!

**Comment by kristian** [comment]
Hello Richi,

you are right, I think your's will perform better. But I think I will stick
with:

"(?:[^"\]|\.)*"

It works with:
"Test"
"Test\"Test"
and "Test\"

Thanks a lot for your information, I will push a new version to github in a
minute.

Regards,
Kristian
2012/9/1 richi notifications@github.com
